export const ACH_READY_REQUEST = "ACH_READY_REQUEST"
export const ACH_READY_SUCCESS = "ACH_READY_SUCCESS"
export const ACH_READY_ERROR = "ACH_READY_ERROR"

export const ACH_BANKACCOUNTS_REQUEST = "ACH_BANKACCOUNTS_REQUEST"
export const ACH_BANKACCOUNTS_SUCCESS = "ACH_BANKACCOUNTS_SUCCESS"
export const ACH_BANKACCOUNTS_ERROR = "ACH_BANKACCOUNTS_ERROR"

export const ACH_LINK_BANKACCOUNTS_REQUEST = "ACH_LINK_BANKACCOUNTS_REQUEST"
export const ACH_LINK_BANKACCOUNTS_SUCCESS = "ACH_LINK_BANKACCOUNTS_SUCCESS"
export const ACH_LINK_BANKACCOUNTS_ERROR = "ACH_LINK_BANKACCOUNTS_ERROR"

export const ACH_DEPOSIT_REQUEST = "ACH_DEPOSIT_REQUEST"
export const ACH_DEPOSIT_SUCCESS = "ACH_DEPOSIT_SUCCESS"
export const ACH_DEPOSIT_ERROR = "ACH_DEPOSIT_ERROR"

export const ACH_WITHDRAW_REQUEST = "ACH_WITHDRAW_REQUEST"
export const ACH_WITHDRAW_SUCCESS = "ACH_WITHDRAW_SUCCESS"
export const ACH_WITHDRAW_ERROR = "ACH_WITHDRAW_ERROR"

// Cashflow
export const ACH_GET_WIDGET_REQUEST = "ACH_GET_WIDGET_REQUEST"
export const ACH_GET_WIDGET_SUCCESS = "ACH_GET_WIDGET_SUCCESS"
export const ACH_GET_WIDGET_ERROR = "ACH_GET_WIDGET_ERROR"