export const FIAT_WALLET_CREATE_REQUEST = "FIAT_WALLET_CREATE_REQUEST"
export const FIAT_WALLET_CREATE_SUCCESS = "FIAT_WALLET_CREATE_SUCCESS"
export const FIAT_WALLET_CREATE_ERROR = "FIAT_WALLET_CREATE_ERROR"

export const FIAT_WALLET_LIST_REQUEST = "FIAT_WALLET_LIST_REQUEST"
export const FIAT_WALLET_LIST_SUCCESS = "FIAT_WALLET_LIST_SUCCESS"
export const FIAT_WALLET_LIST_ERROR = "FIAT_WALLET_LIST_ERROR"

export const FIAT_WALLET_PAY_REQUEST = "FIAT_WALLET_PAY_REQUEST"
export const FIAT_WALLET_PAY_SUCCESS = "FIAT_WALLET_PAY_SUCCESS"
export const FIAT_WALLET_PAY_ERROR = "FIAT_WALLET_PAY_ERROR"

export const FIAT_WALLET_DEPOSIT_REQUEST = "FIAT_WALLET_DEPOSIT_REQUEST"
export const FIAT_WALLET_DEPOSIT_SUCCESS = "FIAT_WALLET_DEPOSIT_SUCCESS"
export const FIAT_WALLET_DEPOSIT_ERROR = "FIAT_WALLET_DEPOSIT_ERROR"

// export const WALLET_WITHDRAW_REQUEST = "WALLET_WITHDRAW_REQUEST"
// export const WALLET_WITHDRAW_SUCCESS = "WALLET_WITHDRAW_SUCCESS"
// export const WALLET_WITHDRAW_ERROR = "WALLET_WITHDRAW_ERROR"

export const FIAT_WALLET_DELETE_REQUEST = "FIAT_WALLET_DELETE_REQUEST"
export const FIAT_WALLET_DELETE_SUCCESS = "FIAT_WALLET_DELETE_SUCCESS"
export const FIAT_WALLET_DELETE_ERROR = "FIAT_WALLET_DELETE_ERROR"

// export const WALLETS_STAT_REQUEST = "WALLETS_STAT_REQUEST"
// export const WALLETS_STAT_SUCCESS = "WALLETS_STAT_SUCCESS"
// export const WALLETS_STAT_ERROR = "WALLETS_STAT_ERROR"