export const ORDER_CHANGE_SELLCURRENCY = "ORDER_CHANGE_SELLCURRENCY"
export const ORDER_CHANGE_SELLAMOUNT = "ORDER_CHANGE_SELLAMOUNT"
export const ORDER_CHANGE_BUYCURRENCY = "ORDER_CHANGE_BUYCURRENCY"
export const ORDER_CHANGE_BUYAMOUNT = "ORDER_CHANGE_BUYAMOUNT"
export const ORDER_CHANGE_DIRECTION = "ORDER_CHANGE_DIRECTION"
export const ORDER_CHANGE_ADDRESS = "ORDER_CHANGE_ADDRESS"
export const ORDER_CLEAR = "ORDER_CLEAR"

export const ORDER_CALCULATE_REQUEST = "ORDER_CALCULATE_REQUEST"
export const ORDER_CALCULATE_SUCCESS = "ORDER_CALCULATE_SUCCESS"
export const ORDER_CALCULATE_ERROR = "ORDER_CALCULATE_ERROR"

export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST"
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS"
export const ORDER_CREATE_ERROR = "ORDER_CREATE_ERROR"

export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST"
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS"
export const ORDER_LIST_ERROR = "ORDER_LIST_ERROR"

export const ORDER_DAILYLIMIT_REQUEST = "ORDER_DAILYLIMIT_REQUEST"
export const ORDER_DAILYLIMIT_SUCCESS = "ORDER_DAILYLIMIT_SUCCESS"
export const ORDER_DAILYLIMIT_ERROR = "ORDER_DAILYLIMIT_ERROR"

export const ORDER_TX_REQUEST = "ORDER_TX_REQUEST"
export const ORDER_TX_SUCCESS = "ORDER_TX_SUCCESS"
export const ORDER_TX_ERROR = "ORDER_TX_ERROR"

export const ORDER_PRESELECT_CURRENCIES = "ORDER_PRESELECT_CURRENCIES"