export const WALLET_CREATE_REQUEST = "WALLET_CREATE_REQUEST"
export const WALLET_CREATE_SUCCESS = "WALLET_CREATE_SUCCESS"
export const WALLET_CREATE_ERROR = "WALLET_CREATE_ERROR"

export const WALLET_LIST_REQUEST = "WALLET_LIST_REQUEST"
export const WALLET_LIST_SUCCESS = "WALLET_LIST_SUCCESS"
export const WALLET_LIST_ERROR = "WALLET_LIST_ERROR"

export const WALLET_WITHDRAW_REQUEST = "WALLET_WITHDRAW_REQUEST"
export const WALLET_WITHDRAW_SUCCESS = "WALLET_WITHDRAW_SUCCESS"
export const WALLET_WITHDRAW_ERROR = "WALLET_WITHDRAW_ERROR"

export const WALLET_DELETE_REQUEST = "WALLET_DELETE_REQUEST"
export const WALLET_DELETE_SUCCESS = "WALLET_DELETE_SUCCESS"
export const WALLET_DELETE_ERROR = "WALLET_DELETE_ERROR"

export const WALLETS_STAT_REQUEST = "WALLETS_STAT_REQUEST"
export const WALLETS_STAT_SUCCESS = "WALLETS_STAT_SUCCESS"
export const WALLETS_STAT_ERROR = "WALLETS_STAT_ERROR"

export const CHANGE_WALLET_PIN_REQUEST = "CHANGE_WALLET_PIN_REQUEST"
export const CHANGE_WALLET_PIN_SUCCESS = "CHANGE_WALLET_PIN_SUCCESS"
export const CHANGE_WALLET_PIN_ERROR = "CHANGE_WALLET_PIN_ERROR"

export const RESET_WALLET_PIN_REQUEST = "RESET_WALLET_PIN_REQUEST"
export const RESET_WALLET_PIN_SUCCESS = "RESET_WALLET_PIN_SUCCESS"
export const RESET_WALLET_PIN_ERROR = "RESET_WALLET_PIN_ERROR"