export const COUNTRIES_REQUEST = "COUNTRIES_REQUEST"
export const COUNTRIES_ERROR = "COUNTRIES_ERROR"
export const COUNTRIES_SUCCESS = "COUNTRIES_SUCCESS"

export const STATES_REQUEST = "STATES_REQUEST"
export const STATES_ERROR = "STATES_ERROR"
export const STATES_SUCCESS = "STATES_SUCCESS"