// V-MODEL CHANGE
// Personal model change mutations
export const KYC_CHANGE_FIRSTNAME = "KYC_CHANGE_FIRSTNAME"
export const KYC_CHANGE_MIDDLENAME = "KYC_CHANGE_MIDDLENAME"
export const KYC_CHANGE_LASTNAME = "KYC_CHANGE_LASTNAME"
export const KYC_CHANGE_GENDER = "KYC_CHANGE_GENDER"
export const KYC_CHANGE_BIRTHDATE = "KYC_CHANGE_BIRTHDATE"
export const KYC_CHANGE_BIRTHPLACE = "KYC_CHANGE_BIRTHPLACE"
// Address model change mutations
export const KYC_CHANGE_ADDRESSCOUNTRY = "KYC_CHANGE_ADDRESSCOUNTRY"
export const KYC_CHANGE_REGION = "KYC_CHANGE_REGION"
export const KYC_CHANGE_ZIPCODE = "KYC_CHANGE_ZIPCODE"
export const KYC_CHANGE_CITY = "KYC_CHANGE_CITY"
export const KYC_CHANGE_STREET = "KYC_CHANGE_STREET"
// IndentityDocument model change mutations
export const KYC_CHANGE_IDENTITYCOUNTRY = "KYC_CHANGE_IDENTITYCOUNTRY"
export const KYC_CHANGE_NUMBER = "KYC_CHANGE_NUMBER"
export const KYC_CHANGE_AUTHORITY = "KYC_CHANGE_AUTHORITY"
export const KYC_CHANGE_DATEOFISSUE = "KYC_CHANGE_DATEOFISSUE"
export const KYC_CHANGE_DATEOFEXPIRE = "KYC_CHANGE_DATEOFEXPIRE"
export const KYC_CHANGE_SSN = "KYC_CHANGE_SSN"
export const KYC_CHANGE_IDNAME = "KYC_CHANGE_IDNAME"

// TAB FIELDS
// Personal model GET/SAVE mutations
export const KYC_GET_PERSONAL_REQUEST = "KYC_GET_PERSONAL_REQUEST"
export const KYC_GET_PERSONAL_SUCCESS = "KYC_GET_PERSONAL_SUCCESS"
export const KYC_SAVE_PERSONAL_REQUEST = "KYC_SAVE_PERSONAL_REQUEST"
// Address model GET/SAVE mutations
export const KYC_GET_ADDRESS_REQUEST = "KYC_GET_ADDRESS_REQUEST"
export const KYC_GET_ADDRESS_SUCCESS = "KYC_GET_ADDRESS_SUCCESS"
export const KYC_SAVE_ADDRESS_REQUEST = "KYC_SAVE_ADDRESS_REQUEST"
// IndentityDocument model GET/SAVE mutations
export const KYC_GET_IDENTITY_REQUEST = "KYC_GET_IDENTITY_REQUEST"
export const KYC_GET_IDENTITY_SUCCESS = "KYC_GET_IDENTITY_SUCCESS"
export const KYC_SAVE_IDENTITY_REQUEST = "KYC_SAVE_IDENTITY_REQUEST"
// Webcam screenplay GET mutations
export const KYC_GET_SCREENPLAY_REQUEST = "KYC_GET_SCREENPLAY_REQUEST"
export const KYC_GET_SCREENPLAY_SUCCESS = "KYC_GET_SCREENPLAY_SUCCESS"
// SSN GET/SAVE mutations
export const KYC_GET_SSN_REQUEST = "KYC_GET_SSN_REQUEST"
export const KYC_GET_SSN_SUCCESS = "KYC_GET_SSN_SUCCESS"
export const KYC_SAVE_SSN_REQUEST = "KYC_SAVE_SSN_REQUEST"

// FILES
// IndentityDocument file GET/SAVE mutations
export const KYC_GET_IDDOC_REQUEST = "KYC_GET_IDDOC_REQUEST"
export const KYC_GET_IDDOC_REQUEST_BACK = "KYC_GET_IDDOC_REQUEST_BACK"
export const KYC_GET_IDDOC_SUCCESS = "KYC_GET_IDDOC_SUCCESS"
export const KYC_GET_IDDOC_BACK_SUCCESS = "KYC_GET_IDDOC_BACK_SUCCESS"
export const KYC_SAVE_IDDOC_REQUEST = "KYC_SAVE_IDDOC_REQUEST"
export const KYC_SAVE_IDDOC_REQUEST_BACK = "KYC_SAVE_IDDOC_REQUEST_BACK"
export const KYC_SAVE_IDDOC_SUCCESS = "KYC_SAVE_IDDOC_SUCCESS"
export const KYC_SAVE_IDDOC_BACK_SUCCESS = "KYC_SAVE_IDDOC_BACK_SUCCESS"
// Webcam user's video GET/SAVE mutations
export const KYC_GET_VIDEO_REQUEST = "KYC_GET_VIDEO_REQUEST"
export const KYC_GET_VIDEO_SUCCESS = "KYC_GET_VIDEO_SUCCESS"
export const KYC_SAVE_VIDEO_REQUEST = "KYC_SAVE_VIDEO_REQUEST"
export const KYC_SAVE_VIDEO_SUCCESS = "KYC_SAVE_VIDEO_SUCCESS"

// SelfieDocument file GET/SAVE mutations
export const KYC_GET_SELFIEWITHID_REQUEST = "KYC_GET_SELFIEWITHID_REQUEST"
export const KYC_GET_SELFIEWITHID_SUCCESS = "KYC_GET_SELFIEWITHID_SUCCESS"
export const KYC_SAVE_SELFIEWITHID_REQUEST = "KYC_SAVE_SELFIEWITHID_REQUEST"
export const KYC_SAVE_SELFIEWITHID_SUCCESS = "KYC_SAVE_SELFIEWITHID_SUCCESS"
// ProofResidence file GET/SAVE mutations
export const KYC_GET_PROOFOFRESIDENCE_REQUEST = "KYC_GET_PROOFOFRESIDENCE_REQUEST"
export const KYC_GET_PROOFOFRESIDENCE_SUCCESS = "KYC_GET_PROOFOFRESIDENCE_SUCCESS"
export const KYC_SAVE_PROOFOFRESIDENCE_REQUEST = "KYC_SAVE_PROOFOFRESIDENCE_REQUEST"
export const KYC_SAVE_PROOFOFRESIDENCE_SUCCESS = "KYC_SAVE_PROOFOFRESIDENCE_SUCCESS"
// Certificate file GET/SAVE mutations
export const KYC_GET_CERTIFICATE_REQUEST = "KYC_GET_CERTIFICATE_REQUEST"
export const KYC_GET_CERTIFICATE_SUCCESS = "KYC_GET_CERTIFICATE_SUCCESS"
export const KYC_SAVE_CERTIFICATE_REQUEST = "KYC_SAVE_CERTIFICATE_REQUEST"
export const KYC_SAVE_CERTIFICATE_SUCCESS = "KYC_SAVE_CERTIFICATE_SUCCESS"

// GENERAL
// KYC general mutations
export const KYC_GET_ERROR = "KYC_GET_ERROR"
export const KYC_SAVE_ERROR = "KYC_SAVE_ERROR"
export const KYC_SAVE_SUCCESS = "KYC_SAVE_SUCCESS"

// Send to check agent
export const KYC_CHECK_REQUEST = "KYC_CHECK_REQUEST"
export const KYC_CHECK_ERROR = "KYC_CHECK_ERROR"
export const KYC_CHECK_SUCCESS = "KYC_CHECK_SUCCESS"
